require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"angular",
		"bash",
		"c",
		-- "cpp",
		"c_sharp",
		"css",
		"go",
		"gomod",
		"gosum",
		"gotmpl",
        "gleam",
		"haskell",
		"html",
		"java",
		"javascript",
		"json",
		"json5",
		"kotlin",
		-- "latex",
		"lua",
		"luadoc",
		"make",
		-- "markdown",
		"ocaml",
		"printf",
		"prisma",
		"proto",
		"python",
		"regex",
		"rust",
		"scss",
		"sql",
		"toml",
		-- "vim",
		"vimdoc",
		"xml",
		"yaml",
		"zig",
	},
	sync_install = true,
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "gnn",
			node_incremental = "gni",
			scope_incremental = "gns",
			node_decremental = "gnd",
		},
	},
	indent = {
		enable = false,
	},
	highlight = {
		enable = true,
		disable = { "latex", "rst" },
	},
	playground = {
		enable = true,
		updatetime = 25,
		persist_queries = true,
		keybindings = {
			toggle_query_editor = "o",
			toggle_hl_groups = "i",
			toggle_injected_languages = "t",
			toggle_anonymous_nodes = "a",
			toggle_language_display = "I",
			focus_language = "f",
			unfocus_language = "F",
			update = "R",
			goto_node = "<cr>",
			show_help = "?",
		},
	},
	query_linter = {
		enable = true,
		use_virtual_text = true,
		lint_events = { "BufWrite", "CursorHold" },
	},
	textobjects = {
		enable = true,
		select = {
			enable = true,
			keymaps = {
				["af"] = "@function.outer",
				["if"] = "@function.inner",
				["ac"] = "@class.outer",
				["ic"] = "@class.inner",
			},
		},
		swap = {
			enable = true,
			swap_next = {
				["<leader>si"] = "@parameter.inner",
			},
			swap_previous = {
				["<leader>sA"] = "@parameter.inner",
			},
		},
		move = {
			enable = true,
			set_jumps = true,
			goto_next_start = {
				["]f"] = "@function.outer",
				["]]"] = "@class.outer",
			},
			goto_next_end = {
				["]F"] = "@function.outer",
				["]["] = "@class.outer",
			},
			goto_previous_start = {
				["[f"] = "@function.outer",
				["[["] = "@class.outer",
			},
			goto_previous_end = {
				["[F"] = "@function.outer",
				["[]"] = "@class.outer",
			},
		},
		lsp_interop = {
			enable = true,
			peek_definition_code = {
				["<leader>df"] = "@function.outer",
				["<leader>dF"] = "@class.outer",
			},
		},
	},
	rainbow = {
		enable = true,
		extended_mode = true,
		max_file_lines = nil,
	},
	autotag = {
		enable = true,
	},
})
